# Darwin makefile configuration

OPENHTML := open

installpackages:
	brew install python postgresql nodejs npm wget
	pip install virtualenv
	npm install -g bower grunt grunt-cli
	gem install sass # you may need to run as root
